# Meta-data of ndarrays


## ndarray

- .ndim
- .shape -> .reshape, .resize , .flatten , .ravel
- .size
- .dtype
- .itemsize -> .astype
- .nbytes

In [5]:
import numpy as np

# ndim
scalar_np = np.array(3.14)
vector_np = np.array([1,2,3])
matrix_np = np.array([[1,2],[3,4]])
tensor_np = np.array([[[1,2,3],
                      [4,5,6]],
                     [[11, 12, 13],
                     [14, 15, 16]]])

print(scalar_np.ndim) # 0 dimension
print(vector_np.ndim) # 1 dimension
print(matrix_np.ndim) # 2 dimension
print(tensor_np.ndim) # 3 dimension

0
1
2
3


In [10]:
# shape

print("shape / dimension")
print(f"{scalar_np.shape} / {len(scalar_np.shape)}") 
print(f"{vector_np.shape}/ {len(vector_np.shape)}")
print(f"{matrix_np.shape}/ {len(matrix_np.shape)}")
print(f"{tensor_np.shape}/ {len(tensor_np.shape)}")


a = np.array([1,2,3])
b = np.array([[1,2,3]]) # 2차원 텐서
c = np.array([[1],[2],[3]]) # 2차원 텐서

print("\n")
print(a, a.shape)
print(b, b.shape)
print(c, c.shape)

shape / dimension
() / 0
(3,)/ 1
(2, 2)/ 2
(2, 2, 3)/ 3


[1 2 3] (3,)
[[1 2 3]] (1, 3)
[[1]
 [2]
 [3]] (3, 1)


In [ ]:
# size


# 전체 원소의 갯수 (n*m*o..)
M = np.ones(shape = (10,))
N = np.ones(shape = (3, 4))
O = np.ones(shape = (3, 4, 5))
P = np.ones(shape = (3, 4, 5,6))


print("Size of M:", M.size)
print("Size of N:", N.size)
print("Size of O:", O.size)
print("Size of P:", P.size)

## Data types in Numpy

- np.int : np.int8 / np.int16 / np.int32 / np.int64
- np.uint(unsign): 부호가 없는, 즉 양수인 int , np.uint8 / np.uint16 / np.uint32 / np.uint64
- np.float: np.float32 / np.float64

In [16]:
# 이미지의 경우 일반적으로 .uint8
# if 100 X 100 uint8이면 , 10000개의 Byte가 있다. KB = B/1024 if color x3

M = np.arange(100)
N = np.full(fill_value=3.14, shape=(2,3))

print(M.dtype)
print(N.dtype)

int32
float64


In [15]:
int_np = np.array([1,2,3])
float_np = np.array([1.,2.,3.])

print(int_np.dtype)
print(float_np.dtype)


int32
float64


In [18]:
M = np.ones(shape = (2,3), dtype=np.float32)
N = np.zeros_like(M, dtype=np.float64)


print(f"{M.dtype}/{N.dtype}") # 2배의 용량차이!!
print(M)
print(N)

float32/float64
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


- dtype
- itemsize : 배열의 크기
- size: 배열의 요소 전체의 개수
- nbytes: size * itemsize

In [33]:
int8_np = np.array([1,2,3], dtype= np.int8)
int16_np = np.array([1,2,3], dtype= np.int16)
int32_np = np.array([1,2,3], dtype= np.int32)
int64_np = np.array([1,2,3], dtype= np.int64)

print(f"{int8_np.dtype} / {int8_np.itemsize}B") # 1Byte
print(f"{int16_np.dtype} / {int16_np.itemsize}B") # 2Byte
print(f"{int32_np.dtype} / {int32_np.itemsize}B") # 3Byte
print(f"{int64_np.dtype} / {int64_np.itemsize}B") # 4Byte

int8 / 1B
int16 / 2B
int32 / 4B
int64 / 8B


In [34]:
normal = np.random.normal(size=(50,50,32,5))

print("size : ", normal.size)
print(f"dtype/itemsize: {normal.dtype}/{normal.itemsize}\n")


m_cap = normal.size * normal.itemsize

print(f"Memory capacity in B: {m_cap}B") # Momory capacity
print(f"Memory capacity in {m_cap/1024}KB") # Momory capacity
print(f"Memory capacity in {m_cap/1024**2}MB") # Momory capacity

size :  400000
dtype/itemsize: float64/8

Memory capacity in B: 3200000B
Memory capacity in 3125.0KB
Memory capacity in 3.0517578125MB


In [35]:
import numpy as np

normal = np.random.normal(size = (50,50,32,5))

m_cap = normal.size * normal.itemsize
print(f"{m_cap}B / {normal.nbytes}B")

3200000B / 3200000B
