## Changing ndarrays

- .reshape
- .resize
- .flatten
- .ravel
- .astype

- numpy.reshape(a, newshape, order = "C")

In [2]:
import numpy as np

a = np.arange(6)
b = np.reshape(a,(2,3))

print("a : \n", a)
print("b : \n", b)

a : 
 [0 1 2 3 4 5]
b : 
 [[0 1 2]
 [3 4 5]]


In [3]:
a = np.arange(24)
b = np.reshape(a, (2,3,4))

print("a : \n", a)
print("b : \n", b)

a : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
b : 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### np.reshape and ndarray.reshape

In [9]:
import numpy as np

a = np.random.randint(0, 100, (100,))
print(a.shape)

print(a.reshape(20,5).mean(axis= 0).max())
print(np.max(np.mean(np.reshape(a,(20,5)), axis = 0)))

(100,)
57.85
57.85


### -1 in np.reshape

In [10]:
a = np.arange(12)

b = a.reshape((2,-1))
c = a.reshape((3,-1))
d = a.reshape((4,-1))
e = a.reshape((6,-1))

print(b.shape, c.shape, d.shape, e.shape)

(2, 6) (3, 4) (4, 3) (6, 2)


In [11]:
a = np.random.randint(0,10, size=(2,2))

print(a)

row_vector = a.reshape(1,-1)

[[7 8]
 [2 6]]
