## Changing ndarrays

- .reshape
- .resize
- .flatten
- .ravel
- .astype

- numpy.reshape(a, newshape, order = "C")

In [2]:
import numpy as np

a = np.arange(6)
b = np.reshape(a,(2,3))

print("a : \n", a)
print("b : \n", b)

a : 
 [0 1 2 3 4 5]
b : 
 [[0 1 2]
 [3 4 5]]


In [3]:
a = np.arange(24)
b = np.reshape(a, (2,3,4))

print("a : \n", a)
print("b : \n", b)

a : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
b : 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### np.reshape and ndarray.reshape

In [1]:
import numpy as np

a = np.random.randint(0, 100, (100,))
print(a.shape)

print(a.reshape(20,5).mean(axis= 0).max())
print(np.max(np.mean(np.reshape(a,(20,5)), axis = 0)))

(100,)
61.75
61.75


### -1 in np.reshape

In [2]:
a = np.arange(12)

b = a.reshape((2,-1))
c = a.reshape((3,-1))
d = a.reshape((4,-1))
e = a.reshape((6,-1))

print(b.shape, c.shape, d.shape, e.shape)

(2, 6) (3, 4) (4, 3) (6, 2)


In [3]:
a = np.random.randint(0,10, size=(2,2))

print(a)

row_vector = a.reshape(1,-1)

[[6 5]
 [0 1]]


### np.resize and ndarray.resize



__반환타입이 다르다!!!__
- reshape -> ()
- resize -> 100,200

In [5]:

a = np.arange(6)
b = np.resize(a, (2,3))

print("a : \n", a)
print("b : \n", b)

a : 
 [0 1 2 3 4 5]
b : 
 [[0 1 2]
 [3 4 5]]


In [9]:
# # reshape
# a = np.arange(6)
# b = np.reshape(a, (9,)) # error
# print("a : \n", a) 
# print("b : \n", b)


# resize
a = np.arange(6)
b = np.resize(a, (9,)) # ok!
print("a : \n", a) 
print("b : \n", b)


a : 
 [0 1 2 3 4 5]
b : 
 [0 1 2 3 4 5 0 1 2]


In [10]:
# resize
a = np.arange(6)
b = np.resize(a, (3,4)) # ok! # row부터 순서대로 부족하면 처음부터 ~~
print("a : \n", a) 
print("b : \n", b)

a : 
 [0 1 2 3 4 5]
b : 
 [[0 1 2 3]
 [4 5 0 1]
 [2 3 4 5]]


- ndarray.resize(new_shape , refcheck=True)

In [11]:
# resize
a = np.arange(9) # a가 바뀐다.
b = a.resize((2,2)) # return 값이 X
print("a : \n", a) 
print("b : \n", b)

a : 
 [[0 1]
 [2 3]]
b : 
 None


### np.flatten and np.ravel

- ndarray.flatten(order="C")

In [15]:
M = np.arange(9)
N = M.reshape((3,3)) # 항상 바깥쪽 차원부터 연산해야한다.
O = N.flatten()

print(M, "\n")
print(N, "\n")
print(O, "\n")


[0 1 2 3 4 5 6 7 8] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[0 1 2 3 4 5 6 7 8] 



In [13]:
M = np.arange(27)
N = M.reshape((3,3,3))
O = N.flatten()

print(M, "\n") # (3,3), (3,3), (3,3) -> (3,3) -> (3,), (3,), (3,)
print(N, "\n")
print(O, "\n") # 역 연산한다.


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26] 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26] 



In [14]:
N0, N1, N2 = N[0], N[1], N[2]

print(N0)
print(N1)
print(N2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


- np.ravel()

In [16]:
M = np.arange(27)
N = M.reshape((3,3,3))
O = N.ravel()

print(M, "\n") 
print(N, "\n")
print(O, "\n") 


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26] 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26] 



### Copy and view of ndarrays

- 메모리 최적화가 필용하다!!
- Copy(다른 주소값을 가진다.. but 많은 메모리 사용) <-----> View(최적화, 같은 주소값을 공유한다. 즉 하나의 메모리 공유)

In [18]:
a = np.arange(5)
b = a.view()

b[0] = 100

print(a)
print(b)

[100   1   2   3   4]
[100   1   2   3   4]


In [19]:
a = np.arange(5)
b = a[0:3] # slicing은 view이다!!!!

b[...] = 10

print(a) 
print(b)

[10 10 10  3  4]
[10 10 10]


In [20]:
a = np.arange(5)
b = a.copy() # 다른 메모리주소

b[0] = 101

print(a) 
print(b)

[0 1 2 3 4]
[101   1   2   3   4]


In [21]:
# base if ndarrays

a = np.arange(5)
b = a.copy()
c = a.view()
d = a[0:3]

print(b.base is a)
print(c.base is a)
print(d.base is a)

False
True
True


- APIs and copy, view

In [22]:
a = np.arange(5)
b = np.resize(a,(2,2)) #copy

b[0,0] = 100
print(b.base is a, "\n")
print(a)
print(b)

False 

[0 1 2 3 4]
[[100   1]
 [  2   3]]


In [25]:
a = np.random.randint(0,10, (2,3))
b = a.flatten() # copy
b[0] = -10

print(b.base is a, "\n")
print(a)
print(b)


False 

[[3 6 4]
 [6 2 7]]
[-10   6   4   6   2   7]


In [27]:
a = np.random.randint(0,10, (2,3))
b = a.ravel() # 같은 메모리 사용
b[0] = -10

print(b.base is a, "\n")
print(a)
print(b)

True 

[[-10   2   0]
 [  8   9   6]]
[-10   2   0   8   9   6]


In [28]:
a = np.random.randint(0,10, (2,3))
b = a.ravel().copy() # 새로운 메모리
b[0] = -10

print(b.base is a, "\n")
print(a)
print(b)

False 

[[5 6 8]
 [7 2 3]]
[-10   6   8   7   2   3]


### ndarray.astype



In [31]:
M = np.array([1,2,3], np.int8)
print(M.dtype)

N = M.astype(np.uint32)
O = M.astype(np.float32)

print(N.dtype)
print(O.dtype)

int8
uint32
float32


In [32]:
M = np.random.uniform(low= -10, high = 10, size = (3,3))
print(M, "\n")
print(M.astype(np.int32))

[[-0.85848675 -8.76151737 -7.77696429]
 [ 4.75606998  0.3499178   3.4720921 ]
 [ 1.49599523  6.46983884 -7.70965736]] 

[[ 0 -8 -7]
 [ 4  0  3]
 [ 1  6 -7]]


In [41]:
# bool dtype ndarrays

bools = np.array([True, False])
print(f"bool: \n{bools}")

print("\n")
bools2ints = bools.astype(np.int64)
print(f"int: \n{bools2ints}")


print("\n")
bools2floats = bools.astype(np.float32)
print(f"floats: \n{bools2floats}")

print("\n")
ints = np.array([-2,-1, 0, 1,2])
ints2bools = ints.astype(np.bool_)
print(f"ints -> bools: \n{ints2bools}")

print("\n")
floats2bools = ints.astype(np.bool_)
print(f"floats -> bools: \n{floats2bools}")

bool: 
[ True False]


int: 
[1 0]


floats: 
[1. 0.]


ints -> bools: 
[ True  True False  True  True]


floats -> bools: 
[ True  True False  True  True]


In [42]:
print(-3 == True, -3 == False)
print(3.14 == True, 3.14 == False)
print(0. == True, 0. == False)
print(1.== True, 1. == False)

False False
False False
False True
True False
