### Vector-vector Case

In [1]:
import numpy as np

a = np.random.randint(-5,5, (5,))
b = np.random.randint(-5, 5, (5,))

print("a: ", a)
print("b: ", b, "\n")

print("a+b: ", a+b)

a:  [ 2 -2  4 -1  1]
b:  [-1  4  1 -5  3] 

a+b:  [ 1  2  5 -6  4]


In [5]:
a = np.random.randint(1,5, (5,))
b = np.random.randint(1, 5, (5,))

print("a + b: ", a + b)
print("a - b: ", a - b)
print("a * b: ", a * b)
print("a / b: ", a / b)
print("a // b: ", a // b)
print("a % b: ", a % b)
print("a ** b: ", a ** b)

a + b:  [5 3 6 7 4]
a - b:  [-1  1 -2  1  0]
a * b:  [ 6  2  8 12  4]
a / b:  [0.66666667 2.         0.5        1.33333333 1.        ]
a // b:  [0 2 0 1 1]
a % b:  [2 0 2 1 0]
a ** b:  [ 8  2 16 64  4]


In [7]:
print("a + b: ", a.__add__(b))
print("a - b: ", a.__sub__(b))
print("a * b: ", a.__mul__(b))
print("a / b: ", a .__truediv__(b))
print("a // b: ", a.__floordiv__(b))
print("a % b: ", a % b)
print("a ** b: ", a ** b)

a + b:  [5 3 6 7 4]
a - b:  [-1  1 -2  1  0]
a * b:  [ 6  2  8 12  4]
a / b:  [0.66666667 2.         0.5        1.33333333 1.        ]
a // b:  [0 2 0 1 1]
a % b:  [2 0 2 1 0]
a ** b:  [ 8  2 16 64  4]


### Matrix-matrix Case

In [ ]:
M = np.random.randint(1,5, (2,3))
N = np.random.randint(1, 5, (2,3))

print("M: \n", M)
print("N: \n", N , "\n")

print("M + N: \n", M + N)
print("M - N: \n", M - N)

### Element-wise Multiplication and Masking

In [13]:
a = np.arange(5)
mask = np.array([0,1,0,1,0])

print("input : ", a)
print("mask: ", mask)
print("output: ", a * mask) # 원하는 부분만 0으로,,! ex. max_pooling에서 [[2,7],[8,10]] -> [[0,0],[0,1]] bacause of back proporgatino..

input :  [0 1 2 3 4]
mask:  [0 1 0 1 0]
output:  [0 1 0 3 0]


In [17]:
a = np.arange(1, 5).reshape((2,2))
mask = np.array([[0,0],[1,0]])

print("input : \n", a)
print("mask: \n", mask`)
print("output: \n", a * mask)

input : 
 [[1 2]
 [3 4]]
mask: 
 [[0 0]
 [1 0]]
output: 
 [[0 0]
 [3 0]]


### Broadcasting in Numpy

- Broadcasting : shape의 일정하지 않을 때 numpy가 shape을 알아서 맞춰 연산한다.  ex)(3,4)일 때 (3,1) or (1,4)의 연산이 가능해진다. / But bug조심!

- (3,) -> 1차원 텐서 / (1,3) -> 2차원 텐서, (3,1) -> 2차원 텐서 .. 명백히 다르다.


# When ndims Are Equal(Matrices)
- 브로드케스팅이랑 차원을 맞춰서 연산하는 것!
- ex. (3, 3) -> (1, 3) = (3,3)


In [4]:
import numpy as np

# 3,3 / 1,3
A = np.arange(9).reshape(3,3)
B = 10 * np.arange(3).reshape((-1,3))
C = A + B

print(f"A: {A.ndim}/{A.shape}\n{A}")
print("-----------------------")
print(f"B: {B.ndim}/{B.shape}\n{B}")
print("-----------------------")
print(f"A + B: {C.ndim}/{C.shape}\n{C}")

A: 2/(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
-----------------------
B: 2/(1, 3)
[[ 0 10 20]]
-----------------------
A + B: 2/(3, 3)
[[ 0 11 22]
 [ 3 14 25]
 [ 6 17 28]]


In [5]:
# 3,3 / 3,1
A = np.arange(9).reshape(3,3)
B = 10 * np.arange(3).reshape((3,-1))
C = A + B

print(f"A: {A.ndim}/{A.shape}\n{A}")
print("-----------------------")
print(f"B: {B.ndim}/{B.shape}\n{B}")
print("-----------------------")
print(f"A + B: {C.ndim}/{C.shape}\n{C}")

A: 2/(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
-----------------------
B: 2/(3, 1)
[[ 0]
 [10]
 [20]]
-----------------------
A + B: 2/(3, 3)
[[ 0  1  2]
 [13 14 15]
 [26 27 28]]


In [7]:
# 3,1/1,3

A = np.arange(3).reshape((3,-1))
B = 10 * np.arange(3).reshape((-1,3))
C = A + B

print(f"A: {A.ndim}/{A.shape}\n{A}")
print("-----------------------")
print(f"B: {B.ndim}/{B.shape}\n{B}")
print("-----------------------")
print(f"A + B: {C.ndim}/{C.shape}\n{C}")


A: 2/(3, 1)
[[0]
 [1]
 [2]]
-----------------------
B: 2/(1, 3)
[[ 0 10 20]]
-----------------------
A + B: 2/(3, 3)
[[ 0 10 20]
 [ 1 11 21]
 [ 2 12 22]]


In [8]:
# (2,3,3) + (1,3,3)

A = np.arange(18).reshape((2, 3, 3))
B = 10 * np.arange(9).reshape((1, 3, 3))
C = A + B


print(f"A: {A.ndim}/{A.shape}\n{A}")
print("-----------------------")
print(f"B: {B.ndim}/{B.shape}\n{B}")
print("-----------------------")
print(f"A + B: {C.ndim}/{C.shape}\n{C}")

A: 3/(2, 3, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
-----------------------
B: 3/(1, 3, 3)
[[[ 0 10 20]
  [30 40 50]
  [60 70 80]]]
-----------------------
A + B: 3/(2, 3, 3)
[[[ 0 11 22]
  [33 44 55]
  [66 77 88]]

 [[ 9 20 31]
  [42 53 64]
  [75 86 97]]]


In [9]:
# (2,3,3) + (2,1,3)

A = np.arange(18).reshape((2, 3, 3))
B = 10 * np.arange(6).reshape((2, 1, 3))
C = A + B


print(f"A: {A.ndim}/{A.shape}\n{A}")
print("-----------------------")
print(f"B: {B.ndim}/{B.shape}\n{B}")
print("-----------------------")
print(f"A + B: {C.ndim}/{C.shape}\n{C}")

A: 3/(2, 3, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
-----------------------
B: 3/(2, 1, 3)
[[[ 0 10 20]]

 [[30 40 50]]]
-----------------------
A + B: 3/(2, 3, 3)
[[[ 0 11 22]
  [ 3 14 25]
  [ 6 17 28]]

 [[39 50 61]
  [42 53 64]
  [45 56 67]]]


In [10]:
 # (2,3,3)  + (2,3,1)

A = np.arange(18).reshape((2, 3, 3))
B = 10 * np.arange(6).reshape((2, 3, 1))
C = A + B


print(f"A: {A.ndim}/{A.shape}\n{A}")
print("-----------------------")
print(f"B: {B.ndim}/{B.shape}\n{B}")
print("-----------------------")
print(f"A + B: {C.ndim}/{C.shape}\n{C}")

A: 3/(2, 3, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
-----------------------
B: 3/(2, 3, 1)
[[[ 0]
  [10]
  [20]]

 [[30]
  [40]
  [50]]]
-----------------------
A + B: 3/(2, 3, 3)
[[[ 0  1  2]
  [13 14 15]
  [26 27 28]]

 [[39 40 41]
  [52 53 54]
  [65 66 67]]]


### When ndims Are Not Equal

In [17]:
# 3 * (5,)  
a = np.array(3)
u = np.arange(5)

print(f"shapes: {a.shape}/{u.shape}")
print("a: ", a)
print("u: ", u, "\n")


print("a + u", a + u)
print("a - u", a - u)
print("a * u", a * u)
print("a / u", a / u)

print("a > u", a > u)

shapes: ()/(5,)
a:  3
u:  [0 1 2 3 4] 

a + u [3 4 5 6 7]
a - u [ 3  2  1  0 -1]
a * u [ 0  3  6  9 12]
a / u [ inf 3.   1.5  1.   0.75]
a > u [ True  True  True False False]


C:\Users\gi\AppData\Local\Temp/ipykernel_28976/3205222882.py:13: RuntimeWarning: divide by zero encountered in true_divide
  print("a / u", a / u)


In [18]:
# 오른쪽 차원부터 맞춘다..
# (2, ) + (3,2)

A = np.array([10,20])
B = 10 * np.arange(6).reshape((3,2))
C = A + B


print(f"A: {A.ndim}/{A.shape}\n{A}")
print("-----------------------")
print(f"B: {B.ndim}/{B.shape}\n{B}")
print("-----------------------")
print(f"A + B: {C.ndim}/{C.shape}\n{C}")

A: 1/(2,)
[10 20]
-----------------------
B: 2/(3, 2)
[[ 0 10]
 [20 30]
 [40 50]]
-----------------------
A + B: 2/(3, 2)
[[10 30]
 [30 50]
 [50 70]]


In [19]:
# (2,3,4) / (3,4) 연산이 가능한 2차원은 (3,4)뿐이 안된다. 오른쪽 차원부터... !!!


A = np.arange(2*3*4).reshape((2,3,4))
B = 10 * np.arange(3*4).reshape((3,4))
C = A + B


print(f"A: {A.ndim}/{A.shape}\n{A}")
print("-----------------------")
print(f"B: {B.ndim}/{B.shape}\n{B}")
print("-----------------------")
print(f"A + B: {C.ndim}/{C.shape}\n{C}")


A: 3/(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
-----------------------
B: 2/(3, 4)
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]
-----------------------
A + B: 3/(2, 3, 4)
[[[  0  11  22  33]
  [ 44  55  66  77]
  [ 88  99 110 121]]

 [[ 12  23  34  45]
  [ 56  67  78  89]
  [100 111 122 133]]]
