## Indexing and Slicing Vector ndarrays

In [10]:
import numpy as np
    
a = np.arange(10)
print(f"ndarray: \n {a}\n")
    
print(f"a[0]: \n {a[0]}\n")
print(f"a[2]: \n {a[2]}\n")


print(f"a[-1]: \n {a[-1]}\n")
print(f"a[-2]: \n {a[-2]}\n")
print("a[0:3] :", a[0:3])
print("a[3:7] :", a[3:7])
print("a[5:-1] :", a[5:-1])
print("a[::3] :", a[::3])
print("a[7:2:-1] :", a[7:2:-1])
print("a[7:2:-1] :", a[8:3:-2])

ndarray: 
 [0 1 2 3 4 5 6 7 8 9]

a[0]: 
 0

a[2]: 
 2

a[-1]: 
 9

a[-2]: 
 8

a[0:3] : [0 1 2]
a[3:7] : [3 4 5 6]
a[5:-1] : [5 6 7 8]
a[::3] : [0 3 6 9]
a[7:2:-1] : [7 6 5 4 3]
a[7:2:-1] : [8 6 4]


## Element Assignment with Slicing

In [19]:
a = np.arange(10)

indices = np.array([0,3,6,-1])
print(f"ndarray: \n {a}\n")

print(a[indices]) # -1 일때... 9가 나온다.
print(a[a%3==0])

ndarray: 
 [0 1 2 3 4 5 6 7 8 9]

[0 3 6 9]
[0 3 6 9]


In [15]:
a = list(range(1,11))


for data_idx in range(5):
    a[data_idx] = 0
print(a)


[0, 0, 0, 0, 0, 6, 7, 8, 9, 10]


In [17]:
a = np.arange(1,11)
a[:5] = 0
print(a)

a[::2] = 200
print(a)

[ 0  0  0  0  0  6  7  8  9 10]
[200   0 200   0 200   6 200   8 200  10]


## Indexing and Slicing Matrix ndarrays

In [21]:
a = np.arange(12).reshape((3,4))
print(f"ndarray: \n{a}\n")

print("a[0]: ", a[0])

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a[0]:  [0 1 2 3]


In [22]:
image = np.arange(9).reshape((3,3))
print(f"ndarray: \n{image}\n")

horizontal_filp = image[:, ::-1]
print(f"horizontal_filp: \n{horizontal_filp}\n")

vectical_filp = image[::-1, :]
print(f"horizontal_filp: \n{vectical_filp}\n")

rotation_filp = image[::-1, ::-1]
print(f"horizontal_filp: \n{rotation_filp}\n")


ndarray: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

horizontal_filp: 
[[2 1 0]
 [5 4 3]
 [8 7 6]]

horizontal_filp: 
[[6 7 8]
 [3 4 5]
 [0 1 2]]

horizontal_filp: 
[[8 7 6]
 [5 4 3]
 [2 1 0]]



In [25]:
a = np.arange(16).reshape((4,4))

print("a[0,:] : \n", a[0,:])
print("a[0,...] : \n", a[0,...])

a[0,:] : 
 [0 1 2 3]
a[0,...] : 
 [0 1 2 3]


### 3rd Ordet Tensor ndarrays

In [26]:
a = np.arange(3*3*3).reshape((3,3,3))
print(f"ndarray: \n{a}\n")

ndarray: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]



In [28]:
print("a[0, 0] : \n", a[0,0])
print("a[0, 1] : \n", a[0,1])
print("a[0, 2] : \n", a[0,2], "\n")

print("a[1, 0] : \n", a[0,0])
print("a[1, 1] : \n", a[0,1])
print("a[1, 2] : \n", a[0,2], "\n")

a[0, 0] : 
 [0 1 2]
a[0, 1] : 
 [3 4 5]
a[0, 2] : 
 [6 7 8] 

a[1, 0] : 
 [0 1 2]
a[1, 1] : 
 [3 4 5]
a[1, 2] : 
 [6 7 8] 



In [30]:
images = np.random.normal(size=(32,100,200))
print("image set: ", images.shape)

image0 = images[0,:,:]
print(image0.shape)

image set:  (32, 100, 200)
(100, 200)


In [31]:
image0 = images[0,...]
print(image0.shape)

(100, 200)


In [32]:
image0 = images[:,:,0]
print(image0.shape)


image0 = images[...,0]
print(image0.shape)

(32, 100)
(32, 100)


In [33]:
image0 = images[0,:,0]
print(image0.shape)


image0 = images[0,...,0]
print(image0.shape)

(100,)
(100,)


In [36]:
a = np.arange(27).reshape((3,3,3))

print(a[0,:2,:])
print(a[1,:2,:])
print(a[2,:2,:])


[[0 1 2]
 [3 4 5]]
[[ 9 10 11]
 [12 13 14]]
[[18 19 20]
 [21 22 23]]


In [40]:
print(a[:,:,:1])



[[[ 0]
  [ 3]
  [ 6]]

 [[ 9]
  [12]
  [15]]

 [[18]
  [21]
  [24]]]


In [41]:
print(a[1:,-2:,-2:])

[[[13 14]
  [16 17]]

 [[22 23]
  [25 26]]]


In [44]:
# unpacking
image = np.random.normal(size=(3,500,300))
image_r, image_g, image_b = image
print(image_r.shape, image_g.shape, image_b.shape)

(500, 300) (500, 300) (500, 300)


In [49]:
top_left = image[:, :100, :100]
top_right = image[:, :100, -100:]
bottom_left = image[:, -100:, :100]
bottom_right = image[:, -100:, -100:]

print(top_left.shape, top_right.shape)
print(bottom_left.shape, bottom_right.shape)

(3, 100, 100) (3, 100, 100)
(3, 100, 100) (3, 100, 100)


## Indexing and Slicing Vector ndarrays

In [50]:
a = np.arange(10)
print(f"ndarray: \n{a}\n")

indices = np.array([0,3,4])
print(a[indices])


ndarray: 
[0 1 2 3 4 5 6 7 8 9]

[0 3 4]


In [51]:
a = np.arange(10)
print(f"ndarray: \n{a}\n")

indices = np.array([0,0,5,5])
print(a[indices])

ndarray: 
[0 1 2 3 4 5 6 7 8 9]

[0 0 5 5]


In [53]:
a = np.arange(10)
print(f"ndarray: \n{a}\n")

indices = np.array([[1, 2, 3], [5, 8, 9]])
print(a[indices])

ndarray: 
[0 1 2 3 4 5 6 7 8 9]

[[1 2 3]
 [5 8 9]]


In [56]:
a = np.random.randint(0, 20, (10,))
print(f"ndarray: \n {a} \n")

indices = np.random.randint(0, 10, size=(2,3,4))
print(f"indices: \n {indices} \n")
bbbb

print(f"a[indices]: \n {a[indices]} \n")

ndarray: 
 [18 14 10 10  8 16  2  3  0  0] 

indices: 
 [[[4 9 4 8]
  [5 1 2 2]
  [3 3 5 6]]

 [[7 8 6 1]
  [8 9 9 8]
  [4 3 8 8]]] 

a[indices]: 
 [[[ 8  0  8  0]
  [16 14 10 10]
  [10 10 16  2]]

 [[ 3  0  2 14]
  [ 0  0  0  0]
  [ 8 10  0  0]]] 



In [60]:
a = np.arange(12).reshape((3,4))

print(f"ndarray: \n{a}\n")

indices = np.array([0,2]) # (2,)

print(f"indices: \n{indices}")

print(f"indices: \n{a[indices]}") # matrix의 경우 값의 인덱스를 가지고 온다. (2,4)가된다.


ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

indices: 
[0 2]
indices: 
[[ 0  1  2  3]
 [ 8  9 10 11]]


In [61]:
indices = np.array([0,0,1,1,2,2])


print(f"indices: \n{indices}")  # (6,)

print(f"indices: \n{a[indices]}") # \(6,4)

indices: 
[0 0 1 1 2 2]
indices: 
[[ 0  1  2  3]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 8  9 10 11]]


In [63]:
a = np.arange(12).reshape((3,4))

print(f"ndarray: \n{a}\n")

indices = np.array([[0,1,2],[-3,-2,-1]]) # (2,3)
print(f"indices: \n{indices}")  

print(f"indices: \n{a[indices]}") # (2,3,4)가 된다ㅣ...
 

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

indices: 
[[ 0  1  2]
 [-3 -2 -1]]
indices: 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [66]:
a = np.arange(12).reshape((3,4))

print(f"ndarray: \n{a}\n")

indices0, indices1 = np.array([0]), np.array([0])
print(a[indices0, indices1])


indices0, indices1 = np.array([1]), np.array([2])
print(a[indices0, indices1])


indices0, indices1 = np.array([-1]), np.array([0])
print(a[indices0, indices1])


ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[0]
[6]
[8]


In [67]:
a = np.arange(12).reshape((3,4))

print(f"ndarray: \n{a}\n")


indices0, indices1 = np.array([0, 1, 2]), np.array([1, 2, 3])
print(a[indices0, indices1])

ndarray: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[ 1  6 11]


## Indexing with bool ndarrays

In [70]:
 a = np.arange(5)
print(f"ndarray: \n{a}")

b_indices = np.array([True, False, True, False, True])

print(f"b_indices: \n{b_indices}\n") 
print(f"a[b_indices]: \n{a[b_indices]}") 

ndarray: 
[0 1 2 3 4]
b_indices: 
[ True False  True False  True]

a[b_indices]: 
[0 2 4]


In [71]:
 a = np.random.randint(0,20, (10,))
print(f"ndarray: \n{a}")

b_indices = (a % 2 == 0)
print(f"b_indices: \n{b_indices}\n") 

print(f"b_indices: \n{a[b_indices]}\n") 


ndarray: 
[ 7 13 10  7 18 10 18  8  1  7]
b_indices: 
[False False  True False  True  True  True  True False False]

b_indices: 
[10 18 10 18  8]



In [72]:
 a = np.random.randint(0,20, (2,2))
print(f"ndarray: \n{a}")

b_indices = np.array([[True,False],[False, True]])
print(f"b_indices: \n{b_indices}\n") 

print(f"b_indices: \n{a[b_indices]}\n") 


ndarray: 
[[ 9 10]
 [17 16]]
b_indices: 
[[ True False]
 [False  True]]

b_indices: 
[ 9 16]



# Extracting Indices

In [75]:
a = np.array([True, False, True, False])

nonzero = np.nonzero(a)
where = np.where(a)

print(f"a: \n{a}\n")
print(f"nonzero: \n{nonzero}\n")
print(f"where: \n{where}\n") # integer를 반환한다.


a: 
[ True False  True False]

nonzero: 
(array([0, 2], dtype=int64),)

where: 
(array([0, 2], dtype=int64),)



In [77]:
a = np.array([[[True, False, True],
            [True, False, False]],
              
            [[False, True, True],
            [True, False, True]]])

nonzero = np.nonzero(a)
where = np.where(a)

print(f"a: \n{a}\n")
print(f"nonzero: \n{nonzero}\n") # true인 인덱스만 반환해준다.
# [0, 0, 0, 1, 1, 1, 1]  (0,0,0) / (0,0,2) / (0,1,0)...
# [0, 0, 1, 0, 0, 1, 1]
# [0, 2, 0, 1, 2, 0, 2]
print(f"where: \n{where}\n") # integer를 반환한다. , true인 인덱스만 반환해준다.
# [0, 0, 0, 1, 1, 1, 1]  
# [0, 0, 1, 0, 0, 1, 1]
# [0, 2, 0, 1, 2, 0, 2]

a: 
[[[ True False  True]
  [ True False False]]

 [[False  True  True]
  [ True False  True]]]

nonzero: 
(array([0, 0, 0, 1, 1, 1, 1], dtype=int64), array([0, 0, 1, 0, 0, 1, 1], dtype=int64), array([0, 2, 0, 1, 2, 0, 2], dtype=int64))

where: 
(array([0, 0, 0, 1, 1, 1, 1], dtype=int64), array([0, 0, 1, 0, 0, 1, 1], dtype=int64), array([0, 2, 0, 1, 2, 0, 2], dtype=int64))



In [78]:
a = np.random.randint(-2, 3, size = (3,3))

u_nonzero = a[np.nonzero(a)] # ( , )
u_where = a[np.where(a)]
u_bool = a[a != 0]

print(f"a: \n{a}\n")
print(f"u_nonzero: \n{u_nonzero}\n") # 0이 아닌 값들만 나온다.
print(f"u_where: \n{u_where}\n") # 0이 아닌 값들만 나온다. 
print(f"u_bool: \n{u_bool}\n")# bool 타입

a: 
[[ 1 -2  1]
 [-2  1  1]
 [ 2  0  1]]

u_nonzero: 
[ 1 -2  1 -2  1  1  2  1]

u_where: 
[ 1 -2  1 -2  1  1  2  1]

u_bool: 
[ 1 -2  1 -2  1  1  2  1]



In [80]:
a = np.random.randint(-2, 3, size = (3,3))

u_nonzero = a[np.nonzero(a > 0)] 
u_where = a[np.where(a > 0)]
u_bool = a[a > 0]

print(f"a: \n{a}\n")
print(f"u_nonzero: \n{u_nonzero}\n") # 0이 아닌 값들만 나온다.
print(f"u_where: \n{u_where}\n") # 0이 아닌 값들만 나온다. 
print(f"u_bool: \n{u_bool}\n")# bool 타입

a: 
[[-1  2  0]
 [-2 -2  2]
 [-1  0 -2]]

u_nonzero: 
[2 2]

u_where: 
[2 2]

u_bool: 
[2 2]

