# Realated APIs

- np.sum
- np.cumsum
- np.prod
- np.cumprod
- np.diff
- np.mean
- np.median
- np.var
- np.var
- np.std
- np.amax
- np.argmax
- np.amin
- np.argmin
- np.sort

In [2]:
import numpy as np

a = np.arange(5)
print(np.sum(a))
print(a.sum())

10
10


In [5]:
a = np.arange(6).reshape((2,-1))
print("ndarray: \n", a)

print("np.sum: ", np.sum(a))
print("ndarray.sum: ", a.sum())

ndarray: 
 [[0 1 2]
 [3 4 5]]
np.sum:  15
ndarray.sum:  15


In [7]:
a = np.arange(12).reshape((3,-1))

sum_ = a.sum(axis = 0)

print(f"ndarray: {sum_.shape}\n{sum_}") # (4,)

ndarray: (4,)
[12 15 18 21]


In [8]:
sum_ = a.sum(axis = 1)

print(f"ndarray: {sum_.shape}\n{sum_}") # (4,)

ndarray: (3,)
[ 6 22 38]


In [9]:
a = np.arange(12).reshape((3,-1))

sum_class = np.sum(a, axis = 0) # 과목별 합을 구했을떄만 브로드케스팅이 가능하다.!!
sum_student = np.sum(a, axis = 1)

print(f"scores: {a.shape}\n{a}")
print(f"sum_class: {sum_class.shape}\n{sum_class}")
print(f"sum_student: {sum_student.shape}\n{sum_student}")

scores: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
sum_class: (4,)
[12 15 18 21]
sum_student: (3,)
[ 6 22 38]


## Keepdims Argument

In [11]:
a = np.arange(12).reshape((3,-1))

sum_class = np.sum(a, axis = 0, keepdims = True) # 과목별 합을 구했을떄만 브로드케스팅이 가능하다.!!
sum_student = np.sum(a, axis = 1, keepdims = True)

print(f"scores: {a.shape}\n{a}")
print(f"sum_class: {sum_class.shape}\n{sum_class}") # 차원을 남겨준다. 기존의 값과 브로드케스팅 가능
print(f"sum_student: {sum_student.shape}\n{sum_student}")# 차원을 남겨준다. 기존의 값과 브로드케스팅 가능

scores: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
sum_class: (1, 4)
[[12 15 18 21]]
sum_student: (3, 1)
[[ 6]
 [22]
 [38]]


In [15]:
n_stu, n_cls = 3, 4
m_score, M_score = 0, 100
scores = np.random.randint(low = m_score,
                          high = M_score,
                          size = (n_stu, n_cls))

mean_cls = np.mean(scores, axis = 0 , keepdims=True)
mean_stu = np.mean(scores, axis = 1 , keepdims=True)

print(mean_cls,"///",mean_cls.shape)
print(mean_stu, "///",mean_stu.shape)

[[47.33333333 72.66666667 43.66666667 80.        ]] /// (1, 4)
[[79.5 ]
 [43.5 ]
 [59.75]] /// (3, 1)


# 3rd Order Tensor Case

In [16]:
a = np.arange(2*3*4).reshape((2,3,4))

sum_ = a.sum(axis = 0)

print(f"ndarray: {a.shape}\n{a}") # (4,)
print(f"ndarray.sum(axis = 0): {sum_.shape}\n{sum_}") # 0번쨰 차원이 없어진다..라고 생각하면 될듯



ndarray: (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
ndarray.sum(axis = 0): (3, 4)
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [22]:
sum_ = a.sum(axis = 1)
print(f"ndarray.sum(axis = 1): {sum_.shape}\n{sum_}") # 2번쨰 차원이 없어진다..ㅎ (2,4)가 되는것이고 3부분이 합쳐진다.

sum_ = a.sum(axis = 1, keepdims=True)
print(f"ndarray.sum(axis = 1, keepdims=True): {sum_.shape}\n{sum_}") #(2, 1, 4)

ndarray.sum(axis = 1): (2, 4)
[[12 15 18 21]
 [48 51 54 57]]
ndarray.sum(axis = 1, keepdims=True): (2, 1, 4)
[[[12 15 18 21]]

 [[48 51 54 57]]]


In [23]:
sum_ = a.sum(axis = 2)
print(f"ndarray.sum(axis = 1): {sum_.shape}\n{sum_}") # 3번쨰 차원이 없어진다.. row 별로 없어진다.

sum_ = a.sum(axis = 2, keepdims=True)
print(f"ndarray.sum(axis = 1, keepdims=True): {sum_.shape}\n{sum_}") #(2, 1, 4)

ndarray.sum(axis = 1): (2, 3)
[[ 6 22 38]
 [54 70 86]]
ndarray.sum(axis = 1, keepdims=True): (2, 3, 1)
[[[ 6]
  [22]
  [38]]

 [[54]
  [70]
  [86]]]


In [25]:
n_testtime, n_stu, n_cls = 4, 3, 4
m_score, M_score = 0, 100
scores = np.random.randint(low = m_score,
                          high = M_score,
                          size = (n_testtime, 
                                  n_stu,
                                  n_cls))

print("scores: \n", scores)


score_mean = np.mean(scores, axis = 0)
print("score mean: ", 
     score_mean.shape, "\n", # (3,4) 학생과 과목
     score_mean)


scores: 
 [[[44 73 33 92]
  [63 20 93 64]
  [26 22 23 40]]

 [[90 56 78 68]
  [97 36 11  1]
  [16 62 46 97]]

 [[66 80 30 50]
  [71 22 61 36]
  [81 28 62 45]]

 [[96 21 28 98]
  [46 51 92 51]
  [ 9 33 19 29]]]
score mean:  (3, 4) 
 [[74.   57.5  42.25 77.  ]
 [69.25 32.25 64.25 38.  ]
 [33.   36.25 37.5  52.75]]


In [26]:
n_testtime, n_stu, n_cls = 4, 3, 4
m_score, M_score = 0, 100
scores = np.random.randint(low = m_score,
                          high = M_score,
                          size = (n_testtime, 
                                  n_stu,
                                  n_cls))

print("scores: \n", scores)


score_mean = np.mean(scores, axis = 1)
print("score mean: ", 
     score_mean.shape, "\n", # (4,4) 모의고사, 과목
     score_mean)

scores: 
 [[[18 53 90 51]
  [30 65 12 74]
  [33 38 79  1]]

 [[90 51 87 97]
  [63 24 12  6]
  [56 10 66  2]]

 [[99 54 75 78]
  [86 59 71 61]
  [ 3 77 75 65]]

 [[68 44 50 31]
  [31 12 70 26]
  [88  7 52 86]]]
score mean:  (4, 4) 
 [[27.         52.         60.33333333 42.        ]
 [69.66666667 28.33333333 55.         35.        ]
 [62.66666667 63.33333333 73.66666667 68.        ]
 [62.33333333 21.         57.33333333 47.66666667]]
